name: 'Setting GitHub Actions Env'
description: 'Setting GitHub Actions Env'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: 14
    - name: get yarn cache dir
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - name: set cache id
      id: id-cache
      run: echo "::set-output name=id::${GITHUB_SHA}"
    - name: echo var
      run: |
        echo ${{ steps.yarn-cache.outputs.dir }}
        echo ${{ steps.id-cache.outputs.id }}
        echo ${GITHUB_SHA}
    - name: yarn cache
      uses: bluelovers/github-actions-cache@2020011001
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ steps.id-cache.outputs.id }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: cached-dmzj
      uses: bluelovers/github-actions-cache@2020011001
      with:
        path: packages/@node-novel/cached-dmzj/test/temp
        key: ${{ runner.os }}-cached-dmzj-${{ steps.id-cache.outputs.id }}
        restore-keys: |
          ${{ runner.os }}-cached-dmzj-
    - name: cached-esjzone
      uses: bluelovers/github-actions-cache@2020011001
      with:
        path: packages/@node-novel/cached-esjzone/test/temp
        key: ${{ runner.os }}-cached-esjzone-${{ steps.id-cache.outputs.id }}
        restore-keys: |
          ${{ runner.os }}-cached-esjzone-
    - name: cached-masiro
      uses: bluelovers/github-actions-cache@2020011001
      with:
        path: packages/@node-novel/cached-masiro/test/temp
        key: ${{ runner.os }}-cached-masiro-${{ steps.id-cache.outputs.id }}
        restore-keys: |
          ${{ runner.os }}-cached-masiro-
    - name: cached-wenku8
      uses: bluelovers/github-actions-cache@2020011001
      with:
        path: packages/@node-novel/cached-wenku8/test/temp
        key: ${{ runner.os }}-cached-wenku8-${{ steps.id-cache.outputs.id }}
        restore-keys: |
          ${{ runner.os }}-cached-wenku8-
    - name: setup git config
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    - name: install deps
      run: |
        yarn run ci:install
        yarn run ci:install:task:cache
    - name: test ci env
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
        ACTIONS_CACHE_URL: ${{ secrets.ACTIONS_CACHE_URL }}
        ACTIONS_RUNTIME_URL: ${{ secrets.ACTIONS_RUNTIME_URL }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MASIRO_USER: ${{ secrets.MASIRO_USER }}
        MASIRO_PASS: ${{ secrets.MASIRO_PASS }}
        WENKU8_USER: ${{ secrets.WENKU8_USER }}
        WENKU8_PASS: ${{ secrets.WENKU8_PASS }}
      run: yarn run ci:test
    - name: ci:cache:list
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MASIRO_USER: ${{ secrets.MASIRO_USER }}
        MASIRO_PASS: ${{ secrets.MASIRO_PASS }}
        WENKU8_USER: ${{ secrets.WENKU8_USER }}
        WENKU8_PASS: ${{ secrets.WENKU8_PASS }}
      run: yarn run ci:cache:list
