language: node_js
node_js:
  - "node"
  
branches:
  only:
  - master

cache:
  yarn: true
  directories:
    - "node_modules"
    - "packages/@node-novel/cached-dmzj/test/temp"
    - "packages/@node-novel/cached-esjzone/test/temp"
    - "packages/@node-novel/cached-masiro/test/temp"
    - "packages/@node-novel/cached-wenku8/test/temp"

before_install:
  - yarn run ci:install

install:
  - echo install

before_script:
  - echo before_script

script:
  - travis_wait 30 yarn run lerna:prepublish
  - yarn run ci:push
