name: novel-opds-now

on:
  schedule:
    - cron: '0 16 * * 0'
    - cron: '0 16 * * 5'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 14
      - name: install deps
        run: yarn run ci:install
      - name: run script
        env:
          NOW_DEPLOY_HOOK: ${{ secrets.NOW_DEPLOY_HOOK }}
        run: yarn run ci:task:novel-opds-now
