name: check update and publish

on:
  push:
    branches:
      - master
  schedule:
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#scheduled-events-schedule
#            ┌───────────── minute (0 - 59)
#            │ ┌───────────── hour (0 - 23)
#            │ │ ┌───────────── day of the month (1 - 31)
#            │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
#            │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
#            │ │ │ │ │
#            │ │ │ │ │
#            │ │ │ │ │
#            * * * * *
    - cron: '0 0 * * 3'

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@master
      - uses: ./.github/actions/my-env
      - name: run script
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MASIRO_USER: ${{ secrets.MASIRO_USER }}
          MASIRO_PASS: ${{ secrets.MASIRO_PASS }}
          WENKU8_USER: ${{ secrets.WENKU8_USER }}
          WENKU8_PASS: ${{ secrets.WENKU8_PASS }}
          NODE_OPTIONS: --max_old_space_size=8192
        run: yarn run ci:build:3
      - name: ci:cache:list
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MASIRO_USER: ${{ secrets.MASIRO_USER }}
          MASIRO_PASS: ${{ secrets.MASIRO_PASS }}
          WENKU8_USER: ${{ secrets.WENKU8_USER }}
          WENKU8_PASS: ${{ secrets.WENKU8_PASS }}
        run: yarn run ci:cache:list
      - name: Push changes
        if: success()
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
#        with:
#          args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.'
