name: login task

on:
  schedule:
    - cron: '0 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: node
      - name: install deps
        run: yarn run ci:install
      - name: run script
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MASIRO_USER: ${{ secrets.MASIRO_USER }}
          MASIRO_PASS: ${{ secrets.MASIRO_PASS }}
          WENKU8_USER: ${{ secrets.WENKU8_USER }}
          WENKU8_PASS: ${{ secrets.WENKU8_PASS }}
          MY_HASHED_JSON: ${{ secrets.MY_HASHED_JSON }}
        run: yarn run ci:task
      - name: echo
        run: echo ${{github.event_name}}
